server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: busesvenegassa@gmail.com
    password: trpfjnxogwmytgit
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/buses
    username: buses
    password: buses
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
  flyway:
    enabled: false

management.endpoints.web.exposure.include: health,info

mercadopago:
  access-token: APP_USR-7238479622445790-032118-3709446eeac94e8501a6672bb60e2308-3283381858
