server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/buses}
    username: ${SPRING_DATASOURCE_USERNAME:buses}
    password: ${SPRING_DATASOURCE_PASSWORD:buses}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
  flyway:
    enabled: false

management.endpoints.web.exposure.include: health,info

mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN}
